### ISSUE TITLE
can i remove androidx?

### ISSUE THREAD

**Issue by auag0** [fankes/YukiHookAPI#74]
if androidx is enabled, building time is so long and big apk size so i want remove androidx but i cannot remove androidx because used androidx this project
how to remove androidx **or** close this issues if cant remove androidx
```gradle.properties
android.useAndroidX=false
```
sorry for bad english

**Comment by fankes** [comment]
we use androidx's annotation @Keep for R8 and Fragment support for androidx.
Dependencies are automatically wired, you cannot control what dependencies gradle needs to import, you can fork this project and replace it with minimal dependencies such as androidx.annotation and androidx.fragment, but this may still cause some problems, we do not recommend removing it fundamentally, because the compilation speed is related to gradle, which cannot be controlled.

**Comment by fankes** [comment]
OK， but support library was outdated

**Comment by fankes** [comment]
Alright🤪
